services:
  - type: web
    name: autopromptr-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_KEY
        generateValue: true

    disk:
      name: autopromptr-data
      mountPath: /opt/render/project/data
      sizeGB: 1

    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin

    buildFilter:
      paths:
        - server.js
        - automation.js
        - package.json
        - package-lock.json
      ignoredPaths:
        - README.md
        - .gitignore
        - "*.md"

databases:
  - name: autopromptr-redis
    plan: starter

notifications:
  - type: slack
    name: deployment-alerts
    config:
      webhook: $SLACK_WEBHOOK_URL
