services:
  - type: web
    name: autopromptr-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health

    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_KEY
        generateValue: true
        
    # Enhanced resource allocation for better performance
    disk:
      name: autopromptr-data
      mountPath: /opt/render/project/data
      sizeGB: 1
      
    # Enhanced scaling settings
    autoDeploy: true
    
    # Enhanced headers for better security
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
        
    # Enhanced build settings
    buildFilter:
      paths:
      - server.js
      - automation.js
      - package.json
      - package-lock.json
      ignoredPaths:
      - README.md
      - .gitignore
      - "*.md"
      
    # Enhanced environment for Puppeteer
    dockerfilePath: ./Dockerfile
    
# Enhanced database for production (optional)
databases:
  - name: autopromptr-redis
    plan: starter
    
# Enhanced notifications
notifications:
  - type: slack
    name: deployment-alerts
    config:
      webhook: $SLACK_WEBHOOK_URL
